/*
BATCH 46
MANAN KHASGIWALE (2013A7PS128P)
ABHINAV AGARWAL (2013A7PS124P)
*/

#include <stdio.h>
#include <stdlib.h>
#include "lexer.h"
#include "parser.h"
#include "symbolTable.h"
#include "ast.h"
#include "typeChecker.h"
int main( int argc, char *argv[] ) {
	FILE *fp = fopen(argv[1],"r");
	FILE *ferr = fopen("error.txt","w");
	FILE *out = fopen("fout.txt","w");
	buffer B = (buffer)malloc(1000*sizeof(char));
	buffersize k = 1000;
	tokenInfo token1;
	int i, line=0;
	int temp = 1;
	int temp1 = 0;
	int* pos = &temp1;
	int* flag = &temp;
	ST *head = NULL;
	ST *tmp = NULL;
	char scope[30], typeLHS[30];
	int temp2 = 0;
	int *flagg = &temp2;
	parseTree *pt = NULL;
	RT *headRT = NULL;
	RT *tempRT = NULL;
	record *tempR = NULL;
	printf("FIRST and FOLLOW set automated: NO\n");
	printf("Both lexical and syntax analysis modules implemented: YES");
	printf("Parse Tree is being Generated.\n");
	printf("Works on Testcases given by you. Not tested on other testcases. But, it shall work.\n");

	
	int option;
	printf("1 :  For printing the token list (on the console) generated by the lexer.\n Each token appears in a new line alongwith the corresponding lexeme and line number.\n");
	printf("2 :  For parsing to verify the syntactic correctness of the parse tree and printing it.\n");
	printf("3 :  To print AST.\n");
	printf("4 :  Comparion of parse tree and syntax tree.\n");
	printf("5 :  For printing Symbol Table.\n");
	printf("Enter option: ");
	scanf("%d", &option);
	
	switch(option) {
		case 1:
			while(!feof(fp)) {
				if(*flag){
					fp = getStream(fp,B,k);
					line = line + 1;
					*flag = 0;
				}
				token1 = getNextToken(B, ferr, line, flag, pos);
				if(token1.line>0){
					printf("%13s\t%20s\t%d\n", token1.token, token1.lexeme, line);
				}
			}
			break;
		case 2:
			//fprintf(out,"");
			printParseTree(parseInputSourceCode(fp,ferr),out);
			printf("Check %s\n", argv[2]);
			//print from fout.txt
			break;
		case 3:
			pt = parseInputSourceCode(fp,ferr);
			printf("AST Creation Started\n");
			createAST(&pt);
			printParseTree(pt,out);
			printf("here reached\n");
			break;
		case 4:
			
			break;
		case 5:
			pt = parseInputSourceCode(fp,ferr);
			createRT(pt, &headRT, scope, flagg, &tempRT, &tempR);
			//printRT(headRT);
			temp2 = 0;
			createST(pt, &head, scope, flagg, &tmp, headRT);
			printST(head);
			break;
		case 6:
			pt = parseInputSourceCode(fp,ferr);
			createRT(pt, &headRT, scope, flagg, &tempRT, &tempR);
			//printRT(headRT);
			temp2 = 0;
			createST(pt, &head, scope, flagg, &tmp, headRT);
			printST(head);
			temp2 = 0;
			printf("here reached\n");
			typeCheck(pt, head, headRT, typeLHS, flagg);
			break;
		default:
			printf("Invalid input.");
			
	}
	fclose(out);
	fclose(ferr);
	fclose(fp);
	return 0;
}
